---
- hosts: test
  remote_user: root

  tasks:

  - name: Stopping the Firewall service
    service: name=firewalld state=stopped enabled=no

  - selinux:
      state: disabled

  - name: Adding Zabbix repository
    yum_repository:
      name: "zabbix\x86_64"
      description: Zabbix Official Repository - x86_64
      baseurl: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/

  - name: Installing the Database
    yum: state=latest name={{ item }}
    with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

  - name: Starting the Database
    service: name=mariadb state=started

  - name: Installing Apache
    yum: state=latest name={{ item }}
    with_items:
    - httpd
    - httpd-devel

  - name: Installing Zabbix Server
    yum: state=latest name={{ item }}
    with_items:
    - php
    - php-cli
    - php-common
    - php-pear
    - php-gd
    - php-mysql
    - php-xml
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-agent
    - zabbix-java-gateway
    - zabbix-get

  - lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^# DBPassword='
      line: 'DBPassword=z@bb1x'

  - lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^# CacheSize=8M'
      line: 'CacheSize=256M'

  - lineinfile:
      path: /etc/httpd/conf.d/zabbix.conf
      regexp: '^        # php_value date.timezone Europe/Riga'
      line: '        php_value date.timezone America/Sao_Paulo'

  - name: Creating the Database
    shell: echo "create database zabbix character set utf8;" | mysql -u root

  - name: Granting Access to the Database
    shell: echo "grant all privileges on zabbix.* to 'zabbix'@'localhost' identified by 'z@bb1x';" | mysql -u root

  - name: Creating Tables in the Database
    shell: zcat /usr/share/doc/zabbix-server-mysql-3.4.5/create.sql.gz | mysql -uzabbix -pz@bb1x zabbix

  - name: Starting Zabbix Server
    service: name=zabbix-server state=started enabled=yes

  - name: Starting the Zabbix Agent
    service: name=zabbix-agent state=started enabled=yes

  - name: Starting Apache
    service: name=httpd state=started enabled=yes
